#pragma once

#define DEFAULT_HOPS_MAX 30
#define DEFAULT_PROBES_PER_HOP 3
#define DEFAULT_RTT_MAX_MS 1000
#define DEFAULT_PACKET_SIZE_BYTES 60
#define DEFAULT_SIMALTANIOUS_PROBES 16
#define DEFAULT_WAIT_SECS 5.0
